#!/usr/bin/env python3
"""
gen_workload.py
AutoFDO pipeline – demo workload source generator

Writes src/workload.c: a branch-heavy iterative merge-sort benchmark.
Called by 'make' to avoid Makefile multi-line heredoc limitations.

Usage:
    python3 gen_workload.py [output_path]
    Default output: src/workload.c
"""
import os
import sys

OUTPUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join("src", "workload.c")

SOURCE = """\
/* Auto-generated benchmark workload for AutoFDO pipeline testing.
 * Iterative merge-sort over 4 M integers, 8 repetitions.
 * Branch-heavy and cache-sensitive: representative for LBR + BOLT profiling.
 *
 * Generated by gen_workload.py — do not edit by hand.                       */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define NELEMS   4000000U
#define REPEATS  8U

/* Merge a[l..m) and a[m..r) in-place using tmp as scratch buffer. */
static void merge(int *restrict a, int *restrict tmp,
                  size_t l, size_t m, size_t r)
{
    size_t i = l, j = m, k = l;
    while (i < m && j < r)
        tmp[k++] = (a[i] <= a[j]) ? a[i++] : a[j++];
    while (i < m) tmp[k++] = a[i++];
    while (j < r) tmp[k++] = a[j++];
    memcpy(a + l, tmp + l, (r - l) * sizeof(int));
}

/* Bottom-up iterative merge-sort over a[0..n). */
static void mergesort(int *restrict a, int *restrict tmp, size_t n)
{
    for (size_t w = 1; w < n; w *= 2)
        for (size_t l = 0; l < n; l += 2 * w)
            merge(a, tmp, l,
                  (l + w     < n) ? l + w     : n,
                  (l + 2 * w < n) ? l + 2 * w : n);
}

int main(void)
{
    int *data = malloc(NELEMS * sizeof(int));
    int *tmp  = malloc(NELEMS * sizeof(int));
    if (!data || !tmp) {
        fputs("OOM\\n", stderr);
        free(data);
        free(tmp);
        return 1;
    }

    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);

    for (unsigned r = 0; r < REPEATS; r++) {
        /* Different seed per pass prevents the branch predictor from
         * saturating on an already-sorted array in subsequent passes. */
        srand(r * 0x9e3779b9u);
        for (size_t i = 0; i < NELEMS; i++)
            data[i] = rand();
        mergesort(data, tmp, NELEMS);
    }

    clock_gettime(CLOCK_MONOTONIC, &t1);
    double sec = (double)(t1.tv_sec  - t0.tv_sec)
               + (double)(t1.tv_nsec - t0.tv_nsec) * 1e-9;
    printf("elapsed: %.3f s\\n", sec);

    free(data);
    free(tmp);
    return 0;
}
"""

os.makedirs(os.path.dirname(OUTPUT) or ".", exist_ok=True)
with open(OUTPUT, "w") as fh:
    fh.write(SOURCE)
print(f"[gen_workload.py] Written: {OUTPUT}")
